import webbrowser, os, time
os.startfile('C:\Program Files (x86)\Mozilla Firefox\\firefox.exe')
time.sleep(1)
webbrowser.open_new_tab('http://fau-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://fsu-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://ucf-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://fgcu-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://gcsc-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://nwfsc-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://broward-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://famu-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://palmm-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://uf-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://fdnl-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://islandora-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://hccfl-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://scf-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://lssc-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://fiu-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://fscj-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://irsc-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://unf-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://usf-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://spc-test.digital.flvc.org/user')
webbrowser.open_new_tab('http://uwf-test.digital.flvc.org/user')
