import webbrowser, os, time
os.startfile('C:\Program Files (x86)\Mozilla Firefox\\firefox.exe')
time.sleep(1)
webbrowser.open_new_tab('https://fau.digital.flvc.org/user')
webbrowser.open_new_tab('https://fsu.digital.flvc.org/user')
webbrowser.open_new_tab('https://ucf.digital.flvc.org/user')
webbrowser.open_new_tab('https://fgcu.digital.flvc.org/user')
webbrowser.open_new_tab('https://gcsc.digital.flvc.org/user')
webbrowser.open_new_tab('https://nwfsc.digital.flvc.org/user')
webbrowser.open_new_tab('https://broward.digital.flvc.org/user')
webbrowser.open_new_tab('https://famu.digital.flvc.org/user')
webbrowser.open_new_tab('https://hccfl.digital.flvc.org/user')
webbrowser.open_new_tab('https://palmm.digital.flvc.org/user')
webbrowser.open_new_tab('https://uf.digital.flvc.org/user')
webbrowser.open_new_tab('https://scf.digital.flvc.org/user')
webbrowser.open_new_tab('https://floradora.digital.flvc.org/user')
webbrowser.open_new_tab('https://fiu.digital.flvc.org/user')
webbrowser.open_new_tab('https://unf.digital.flvc.org/user')
webbrowser.open_new_tab('https://usf.digital.flvc.org/user')
webbrowser.open_new_tab('https://uwf.digital.flvc.org/user')
webbrowser.open_new_tab('https://lssc.digital.flvc.org/user')